### ISSUE TITLE
How will this work without annotations?

### ISSUE THREAD

**Issue by dschissler** [Atriedes/phalcon-restful-webservice#1]
I'm not using annotations because they are comments and get filtered out when compiled with Ion Cube.  I'd like to see about using this for my [Webird](https://github.com/perchlayer/webird) framework as my current API module/controller is rather limited.  I borrowed the code from something that Nikolaus posted but it was a bit too general and I'm not yet at a point where I need to work with Rest yet.  I've never used annotations and they are not useful to me so I'd rather not spend a lot of time learning about something that I won't be using.  Can you provide some alternative setups for projects not using annotations?

**Comment by Djumpen** [comment]
I cant  find out how annotations parse (limits, white-list)?

**Comment by Atriedes** [comment]
@Djumpen please take a look example above its quite easy I think

**Comment by Atriedes** [comment]
Its custom annotation, I parse it manually using phalcon annotation parser.

which phalcon version do you use?

**Comment by Djumpen** [comment]
I am using phalcon 2.0
Just show this parser, thanks)

**Comment by Atriedes** [comment]
here you go https://docs.phalconphp.com/en/latest/reference/annotations.html
