### ISSUE TITLE
Can't get whitelisted for the KeyController.

### ISSUE THREAD

**Issue by zyxep** [Atriedes/phalcon-restful-webservice#4]
Hi.

I have been trying to get the whitelist to work with the KeyController.

I'm testing it on a vagrant setup with bridged network.
I have added my local ip addr the config and i still get "unauthorized".

Even on localhost with "curl -X POST http://127.0.0.1" do i get "Unauthorized".
I have also tried to remove @Whitelist() from the annotations.

I have initialized the database with sphinx so i have api_keys, api_logs and sphinxlog in my database.

**Comment by Atriedes** [comment]
Have you created API KEYS in database? (api_keys table)

make make sure your you have passed your API key in http header (X-API-KEY)

**Comment by zyxep** [comment]
My SQL.

```SQL
CREATE TABLE IF NOT EXISTS `api_keys` (
  `api_key_id` int(11) NOT NULL,
  `key` varchar(64) NOT NULL,
  `level` int(11) NOT NULL DEFAULT '1',
  `ignore_limit` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `api_keys`
--

INSERT INTO `api_keys` (`api_key_id`, `key`, `level`, `ignore_limit`, `created_at`, `updated_at`) VALUES
(1, 'w22149mZN7WWKfaO47N46yv5vz620G09', 1, 0, NULL, NULL);
```

This is from "Advanced Rest Client App" in chrome.
![](http://i.imgur.com/f5n2Ae8.png)

What am i doing wrong then ?

**Comment by Atriedes** [comment]
Hi,

try to change igonore limit to 1 or you can change level to level 10.

**Comment by Atriedes** [comment]
As we talked in IRC this issue must have been solved
