### ISSUE TITLE
example giving fatal error

### ISSUE THREAD

**Issue by parthcanbrand** [Atriedes/phalcon-restful-webservice#5]
I followed the example file.

when I run the api url : http://localhost/apimylexo/v1/example/get
Fatal error Cannot redeclare class ExampleController

if I add  namespace Jowy\Phrest\Controllers; at the top of the script 
I get below error
{
    "error": {
        "code": "GEN-UNAUTHORIZED",
        "http_code": 401,
        "message": "Unauthorized"
    }
}

Please suggest

**Comment by Atriedes** [comment]
401 mean you have authorize using API key,

Also this project using PSR-4 standard so you have to add namespace for each class.
