### ISSUE TITLE
error phalcon 2

### ISSUE THREAD

**Issue by juanpablocs** [Atriedes/phalcon-restful-webservice#6]
Fatal error: Call to undefined method Phalcon\Mvc\Dispatcher::getHandlerClass() in /Users/jpmaster/development/test/phalcon/phalcon-restful-webservice/app/Core/Security.php on line 20

**Comment by Atriedes** [comment]
which phalcon version do you use?

**Comment by juanpablocs** [comment]
Author	Phalcon Team and contributors
Version	2.0.0
Powered by Zephir	Version 0.6.2a

**Comment by Atriedes** [comment]
Hi, just take a look phalcon 2 docs and there is no API changes it should work.

I will give it a test in phalcon 2, thanks for reporting

**Comment by juanpablocs** [comment]
I hope. thanks

**Comment by Atriedes** [comment]
I can confirm it works in phalcon 2.0.5, Im not sure for your error I thinks its phalcon related error. Since Phalcon\Mvc\Dispatcher::getHandlerClass()  API still available in v2
